config/routes.rb
Rails.application.routes.draw do
  root'contacts#welcome'
  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations" }
  resources :chapters
  resources :districts
  resources :contacts do
    collection do
      get :welcome
    end
  end
  resources :visits
  resources :users do
    member do
      post :to_confirm
      post :to_unconfirmed
      post :to_admin
      post :to_user
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:google_oauth2]

  def self.from_omniauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)

    user = signed_in_resource ? signed_in_resource : identity.user

    if user.nil?
      email = auth.info.email

      user = User.where(email: email).first if email

      if user.nil?
        user = User.new(name: auth.info.name.gsub(/\s+/, '_'),
                        email: auth.info.email,
                        password: Devise.friendly_token[0,20])
        user.save!
      end
    end

    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def delete_access_token(auth)
    @graph ||= Koala::Facebook::API.new(auth.credentials.token)
    @graph.delete_connections(auth.uid, "permissions")
  end
  def comfirm?
    is_comfirm
  end

  def to_confirm
    self.update_columns(is_comfirm: true)
  end

  def to_unconfirmed
    self.update_columns(is_comfirm: false)
  end

  def admin?
    is_admin
  end

  def to_admin
    self.update_columns(is_admin: true)
  end

  def to_user
    self.update_columns(is_admin: false)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to new_user_session_path, alert: "無法獲得驗證！"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  def index
    @users = User.all
  end

  def to_confirm
    @user = User.find_by(id: params[:id])
    @user.to_confirm
    redirect_to users_path
  end

  def to_unconfirmed
    @user = User.find_by(id: params[:id])
    @user.to_unconfirmed
    redirect_to users_path
  end

  def to_admin
    @user = User.find_by(id: params[:id])
    @user.to_admin
    redirect_to users_path
  end

  def to_user
    @user = User.find_by(id: params[:id])
    @user.to_user
    redirect_to users_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h2>使用者列表</h2>
<hr>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>姓名</th>
      <th>Email</th>
      <th>權限</th>
      <th colspan="2">認證</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <% if user.comfirm? %>
            已認證
          <% else %>
            尚未認證
          <% end %>
          /
          <% if user.admin? %>
            管理者
          <% else %>
            一般使用者
          <% end %>
        </td>
        <td>
          <% if user.comfirm? %>
            <%= link_to fa_icon("lock", text: "取消認證"), to_unconfirmed_user_path(user), method: :post, class: "btn btn-info btn-xs" %>
          <% else %>
            <%= link_to fa_icon("unlock", text: "完成認證"), to_confirm_user_path(user), method: :post, class: "btn btn-success btn-xs" %>
          <% end %>
          /
          <% if user.admin? %>
            <%= link_to fa_icon("user", text: "轉為使用者"), to_user_user_path(user), method: :post, class: "btn btn-info btn-xs" %>
          <% else %>
            <%= link_to fa_icon("user-secret", text: "轉為管理者"), to_admin_user_path(user), method: :post, class: "btn btn-success btn-xs" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>