config/routes.rb
Rails.application.routes.draw do
  root'contacts#welcome'
  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations" }
  resources :chapters
  resources :districts
  resources :contacts do
    collection do
      get :welcome
    end
  end
  resources :visits
  resources :users do
    member do
      post :to_confirm
      post :to_unconfirmed
      post :to_admin
      post :to_user
    end
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :district
  validates :name, :district_id, presence: true
  has_many :visits, dependent: :destroy
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :find_contact, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:welcome]
  before_action :comfirm_required, except:[:welcome]

  def welcome
  end
  def index
    @districts = District.all
    if params[:district]
      @district = District.find_by(title: params[:district])
      @contacts = @district.contacts
    else
      @contacts = Contact.all
    end
  end

  def show
    @visits = @contact.visits
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to contacts_path(district: @contact.district.title)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      redirect_to contacts_path(district: @contact.district.title)
    else
      render :edit
    end
  end

  def destroy
    @contact.destroy if @contact
    redirect_to contacts_path(district: @contact.district.title)
  end

  private
  def find_contact
    @contact = Contact.find_by(id: params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :cell_phone, :phone, :district_id)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(contact) do |f| %>
  <%= f.association :district, label: "地區" %>
  <%= f.input :name, label: "名稱" %>
  <%= f.input :cell_phone, label: "手機號碼" %>
  <%= f.input :phone, label: "市話號碼" %>
  <hr>
  <div class="form-inline text-center">
    <%= link_to fa_icon("arrow-left", text: "回名單列表"), contacts_path, class: "btn btn-default" %>
    <%= button_tag type: 'submit', class: "btn btn-sm btn-primary" do %>
      <i class="fa fa-check" aria-hidden="true"></i>
      送出
    <% end %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h2>編輯名單</h2>
<hr>
<%= render "form", contact: @contact %>

app/views/contacts/index.html.erb
<h2>
  內西名單
  <%= link_to fa_icon("user-plus", text: "新增名單"), new_contact_path, class: "btn btn-primary btn-sm pull-right" %>
</h2>
<hr>
<ul class="nav nav-tabs">
  <% if !params[:district] %>
    <li role="presentation" class="active"><%= link_to "全部", contacts_path %></a></li>
  <% else %>
    <li role="presentation"><%= link_to "全部", contacts_path %></a></li>
  <% end %>
  <% @districts.each do |district| %>
    <li role="presentation"  class="<%= 'active' if params[:district] == district.title %>"><%= link_to district.title, contacts_path(district: district.title) %></li>
  <% end %>
</ul>
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th>序</th>
      <th>地區</th>
      <th>姓名</th>
      <th>手機</th>
      <th colspan="2">操作</th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each_with_index do |contact, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= contact.district.title %></td>
        <td><%= link_to contact.name, edit_contact_path(contact)%></td>
        <td><%= contact.cell_phone %></td>
        <td><%= link_to fa_icon("pencil", text: "家訪紀錄"), contact_path(contact), class: "btn btn-sm btn-info" %></td>
        <td><%= link_to fa_icon("trash", text: "刪除"), contact_path(contact), method: :delete, data: { confirm: "確定要刪除？" }, class: "btn btn-sm btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contacts/new.html.erb
<h2>新增名單</h2>
<hr>
<%= render "form", contact: @contact %>

app/views/contacts/show.html.erb
<h2>家訪紀錄</h2>
<br>
<table class="table table-bordered">
  <tr>
    <td>姓名：<%= @contact.name %></td>
    <td>支部：<%= @contact.district.chapter.title %></td>
    <td>地區：<%= @contact.district.title %></td>
  </tr>
  <tr>
    <td>手機：<%= @contact.cell_phone %></td>
    <td colspan="2">市話：<%= @contact.phone %></td>
  </tr>
</table>
<%= link_to fa_icon("edit", text: "新增紀錄"), new_visit_path(contact_id: @contact.id), class: "btn btn-sm btn-primary" %>
<table class="table">
  <thead>
    <tr>
      <th class="col-md-1">序</th>
      <th class="col-md-2">時間</th>
      <th class="col-md-7">家訪紀錄</th>
      <th class="col-md-2">刪除</th>
    </tr>
  </thead>
  <tbody>
    <% @visits.each_with_index do |visit, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= link_to visit.visit_time.strftime("%F"), edit_visit_path(visit) %></td>
        <td><%= simple_format(visit.description) %></td>
        <td><%= link_to fa_icon("trash", text: "刪除"), visit_path(visit), method: :delete, data: { confirm: "確定要刪除？" }, class: "btn btn-sm btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<div class="form-inline text-center">
  <%= link_to fa_icon("arrow-left", text: "回名單列表"), contacts_path(district: @contact.district.title), class: "btn btn-default" %>
</div>

app/views/contacts/welcome.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">注意事項</h3>
  </div>
  <div class="panel-body">
    <ol>
      <li>帳號新增後，需待管理者於「系統使用者」功能中認證後，才可使用。</li>
      <li>若點選功能後，還停留在本頁面，表示帳號尚未認證，請通知管理者。</li>
    </ol>
  </div>
</div>