config/routes.rb
Rails.application.routes.draw do
  root'contacts#welcome'
  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations" }
  resources :chapters
  resources :districts
  resources :contacts do
    collection do
      get :welcome
    end
  end
  resources :visits
  resources :users do
    member do
      post :to_confirm
      post :to_unconfirmed
      post :to_admin
      post :to_user
    end
  end
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :chapter
  has_many :contacts
  validates :title, :chapter_id, presence: true
end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  before_action :find_district, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin_required

  def index
    @districts = District.all
  end

  def new
    @district = District.new
  end

  def create
    @district = District.new(district_params)
    if @district.save
      redirect_to districts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @district.update(district_params)
      redirect_to districts_path
    else
      render :edit
    end
  end

  def destroy
    @district.destroy if @district
    redirect_to districts_path
  end

  private
  def find_district
    @district = District.find_by(id: params[:id])
  end

  def district_params
    params.require(:district).permit(:title, :chapter_id)
  end
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/views/districts/_form.html.erb
<%= simple_form_for(district) do |f| %>
  <%= f.association :chapter, label: "支部" %>
  <%= f.input :title, label: "名稱" %>
<% end %>
<hr>
<div class="form-inline text-center">
  <%= link_to fa_icon("arrow-left", text: "回地區列表"), districts_path, class: "btn btn-default" %>
  <%= button_tag type: 'submit', class: "btn btn-sm btn-primary" do %>
    <i class="fa fa-check" aria-hidden="true"></i>
    送出
  <% end %>
</div>

app/views/districts/edit.html.erb
<h2>編輯地區</h2>
<hr>
<%= render "form", district: @district %>

app/views/districts/index.html.erb
<h2>
  地區
  <%= link_to fa_icon("plus", text: "新增地區"), new_district_path, class: "btn btn-primary btn-sm pull-right" %>
</h2>
<hr>
<table class="table table-hover">
  <thead>
    <tr>
      <th>序</th>
      <th>支部名稱</th>
      <th>地區名稱</th>
      <th>刪除</th>
    </tr>
  </thead>
  <tbody>
    <% @districts.each_with_index do |district,index| %>
      <tr>
        <td><%= index + 1  %></td>
        <td><%= district.chapter.title %></td>
        <td><%= link_to district.title, edit_district_path(district) %></td>
        <td><%= link_to fa_icon("trash", text: "刪除"), district_path(district), method: :delete, class: "btn btn-sm btn-danger", data: { confirm: "是否確認要刪除資料？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/districts/new.html.erb
<h2>新增地區</h2>
<hr>
<%= render "form", district: @district %>