config/routes.rb
Rails.application.routes.draw do
  root'contacts#welcome'
  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks", registrations: "registrations" }
  resources :chapters
  resources :districts
  resources :contacts do
    collection do
      get :welcome
    end
  end
  resources :visits
  resources :users do
    member do
      post :to_confirm
      post :to_unconfirmed
      post :to_admin
      post :to_user
    end
  end
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :districts, dependent: :destroy
  validates :title, presence: true
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :find_chapter, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin_required
  def index
    @chapters = Chapter.all
  end

  def new
    @chapter = Chapter.new
  end

  def create
    @chapter = Chapter.new(chapter_params)
    if @chapter.save
      redirect_to chapters_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @chapter.update(chapter_params)
      redirect_to chapters_path
    else
      render :edit
    end
  end

  def destroy
    @chapter.destroy if @chapter
    redirect_to chapters_path
  end

  private
  def find_chapter
    @chapter = Chapter.find_by(id: params[:id])
  end

  def chapter_params
    params.require(:chapter).permit(:title)
  end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= simple_form_for(chapter) do |f| %>
  <%= f.input :title, label: "名稱" %>
<% end %>
<hr>
<div class="form-inline text-center">
  <%= link_to fa_icon("arrow-left", text: "回支部列表"), chapters_path, class: "btn btn-default" %>
  <%= button_tag type: 'submit', class: "btn btn-sm btn-primary" do %>
    <i class="fa fa-check" aria-hidden="true"></i>
    送出
  <% end %>
</div>

app/views/chapters/edit.html.erb
<h2>編輯支部</h2>
<hr>
<%= render "form", chapter: @chapter %>
<br>

app/views/chapters/index.html.erb
<h2>
  支部
  <%= link_to fa_icon("plus", text: "新增支部"), new_chapter_path, class: "btn btn-primary btn-sm pull-right" %>
</h2>
<hr>
<table class="table table-hover">
  <thead>
    <tr>
      <th>序</th>
      <th>名稱</th>
      <th>刪除</th>
    </tr>
  </thead>
  <tbody>
    <% @chapters.each_with_index do |chapter,index| %>
      <tr>
        <td><%= index + 1  %></td>
        <td><%= link_to chapter.title, edit_chapter_path(chapter) %></td>
        <td><%= link_to fa_icon("trash", text: "刪除"), chapter_path(chapter), method: :delete, class: "btn btn-sm btn-danger", data: { confirm: "是否確認要刪除資料？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/chapters/new.html.erb
<h2>新增支部</h2>
<hr>
<%= render "form", chapter: @chapter %>
<br>